# Site
repository: bpcarlos/bpcarlos.github.io
favicon: images/cat.png

# Content configuration version
version: 2

# Personal info
name: Carlos Bravo-Prieto
title: Postdoctoral Researcher
email: x@fu-berlin.de
# website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: charl_bp
github_username: bpcarlos
orcid_username: 0000-0003-1041-2044

# Additional icon links
additional_links:
- title: CV link
  icon: fas fa-pen-to-square
  url: https://bpcarlos.github.io/files/cv.pdf
- title: Google Scholar link
  icon: fab fa-google
  url: https://scholar.google.com/citations?user=6zoV27oAAAAJ&hl=en

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I am a Postdoctoral Researcher at the Dahlem Center for Complex Quantum Systems in the Freie Universität Berlin. In particular, I am currently working in Jens Eisert's group. I got my PhD in quantum computation and information under the supervision of José Ignacio Latorre at the Universitat de Barcelona, where I initially studied a BSc in Physics. I also have an MSc in Photonics from the Institute of Photonics Sciences (ICFO). While doing my PhD, I had the opportunity to work as a researcher in different institutions. I spent my two first years of PhD as a Research Engineer at the Barcelona Supercomputing Center. After, I spent two more years as an Associate Researcher at the Technology Innovation Institute in Abu Dhabi.

  I am highly interested in quantum technologies and, specifically, quantum computing. My research is focused on quantum algorithms, quantum information, condensed matter physics, and machine learning. Without a doubt, what interests me the most is the intersection of the aforementioned topics.
content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Research Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Freie Universität Berlin
        link: https://www.physik.fu-berlin.de/en/einrichtungen/ag/ag-eisert/index.html
        link_text: Dahlem Center for Complex Quantum Systems
        sub_title: Postdoctoral Researcher
        caption: September 2022 - Present
      - layout: top-middle
        title: Technology Innovation Institute
        link: https://www.tii.ae/quantum
        link_text: Quantum Research Center
        sub_title: Associate Researcher
        caption: September 2020 - September 2022
      - layout: top-middle
        title: Los Alamos National Laboratory
        link: https://www.lanl.gov/org/ddste/aldsc/theoretical/index.php
        link_text: Theoretical Division
        sub_title: Student Fellowship
        caption: June 2019 - August 2019
      - layout: top-middle
        title: Barcelona Supercomputing Center
        link: https://www.bsc.es/discover-bsc/organisation/scientific-structure/general-case
        link_text: CASE department
        sub_title: Research Engineer
        caption: September 2018 - September 2020

  - title: Awards and Honors # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: PhD Excellent Cum Laude
        sub_title: Universitat de Barcelona
        link: 2022
      - layout: top-middle
        title: Quantum Computing Summer Fellowship
        sub_title: Los Alamos National Laboratory
        link: 2019
        quote: >
          1/20 awarded internationally.
      - layout: top-middle
        title: Unitary Fund Grant
        link: 2019
        quote: >
          $2k for open-source quantum software development.
      - layout: top-middle
        title: Top contributors of Teach me Qiskit Awards
        sub_title: IBM
        link: 2018
        quote: >
          Implementation of quantum networks for arithmetic operations, from addition to modular exponentiation.

  - title: Publications and Preprints
    layout: text
    content: | # this will include new lines to allow paragraphs
      - <mark>Variational quantum eigensolver for SU(N) fermions</mark>, Mirko Consiglio, Wayne J. Chetcuti, Carlos Bravo-Prieto, Sergi Ramos-Calderer, Anna Minguzzi, José I. Latorre, Luigi Amico, and Tony J. G. Apollaro, *Journal of Physics A: Mathematical and Theoretical* **55**, 265301 (2022). [[Journal]](https://iopscience.iop.org/article/10.1088/1751-8121/ac7016) [[Preprint]](https://arxiv.org/abs/2106.15552)
      
      - Solving systems of boolean multivariate equations with quantum annealing, Sergi Ramos-Calderer, Carlos Bravo-Prieto, Ruge Lin, Emanuele Bellini, Marc Manzano, Nawja Aaraj, and José I. Latorre, *Physical Review Research* **4**, 013096 (2022).

      - **Qibo: a framework for quantum simulation with hardware acceleration**, Stavros Efthymiou, Sergi Ramos-Calderer, Carlos Bravo-Prieto, Adrián Pérez-Salinas, Diego García-Martín, Artur Garcia-Saez, José I. Latorre and Stefano Carrazza, *Quantum Science and Technology* **7**, 015018 (2021).
      
      - <mark>Style-based quantum generative adversarial networks for Monte Carlo events</mark>, C. Bravo-Prieto, J. Baglio, M. Cé, A. Francis, D. M. Grabowska, and S. Carrazza, *arXiv:2110.06933* (2021).
      
      - Carlos Bravo-Prieto, Quantum autoencoders with enhanced data encoding, Machine Learning: Science and Technology 2, 035028 (2021).
      
      - Sergi Ramos-Calderer, Adrián Pérez-Salinas, Diego García-Martín, Carlos Bravo-Prieto, Jorge Cortada, Jordi Planagumà, and José I. Latorre, Quantum unary approach to option pricing, Physical Review A 103, 032414 (2020).
      
      - Carlos Bravo-Prieto, Josep Lumbreras-Zarapico, Luca Tagliacozzo, and José I. Latorre, Scaling of variational quantum circuit depth for condensed matter systems, Quantum 4, 272 (2020).
      
      - Carlos Bravo-Prieto, Diego García-Martín, and José I. Latorre, Quantum singular value decomposer, Physical Review A 101, 062310 (2020).
      
      - Adrián Pérez-Salinas, Diego García-Martín, Carlos Bravo-Prieto, and José I. Latorre, Measuring the tangle of three-qubit states, Entropy, 22, 436 (2020).
      
      - Carlos Bravo-Prieto, Ryan LaRose, Marco Cerezo, Yigit Subaşı, Lukasz Cincio and Patrick J. Coles, Variational quantum linear solver, arXiv:1909.05820 (2019).

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
