# Site
repository: bpcarlos/bpcarlos.github.io
favicon: images/cat.png

# Content configuration version
version: 2

# Personal info
name: Carlos Bravo-Prieto
title: Postdoctoral Researcher at Freie Universität Berlin
email: c.bravo.prieto(at)fu-berlin(dot)de
# website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: charl_bp
github_username: bpcarlos
orcid_username: 0000-0003-1041-2044

# Additional icon links
additional_links:
- title: CV link
  icon: fas fa-pen-square
  url: https://bpcarlos.github.io/files/cv.pdf
- title: Google Scholar link
  icon: fab fa-google
  url: https://scholar.google.com/citations?user=6zoV27oAAAAJ&hl=en

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I am a Postdoctoral Researcher at the Dahlem Center for Complex Quantum Systems in the Freie Universität Berlin. In particular, I am currently working in Jens Eisert's group. I got my PhD in quantum computation and information under the supervision of José Ignacio Latorre at the Universitat de Barcelona, where I initially studied a BSc in Physics. I also have an MSc in Photonics from the Institute of Photonics Sciences (ICFO). While doing my PhD, I had the opportunity to work as a researcher in different institutions. I spent my two first years of PhD as a Research Engineer at the Barcelona Supercomputing Center. After, I spent two more years as an Associate Researcher at the Technology Innovation Institute in Abu Dhabi.

  I am highly interested in quantum technologies and, specifically, quantum computing. My research is focused on quantum algorithms, quantum information, condensed matter physics, and machine learning. Without a doubt, what interests me the most is the intersection of the aforementioned topics.

  &nbsp;  
  <span style="font-size:larger;">**<mark>Education</mark>**</span>
  - PhD in Physics, Universitat de Barcelona (2022)

  - MSc in Photonics, ICFO Institute of Photonic Sciences (2017)

  - BSc in Physics, Universitat de Barcelona (2016)
content:
  - title: Research Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Freie Universität Berlin
        link: https://www.physik.fu-berlin.de/en/einrichtungen/ag/ag-eisert/index.html
        link_text: Dahlem Center for Complex Quantum Systems
        sub_title: Postdoctoral Researcher
        caption: October 2022 - Present
      - layout: top-middle
        title: Technology Innovation Institute
        link: https://www.tii.ae/quantum
        link_text: Quantum Research Center
        sub_title: Associate Researcher
        caption: September 2020 - September 2022
      - layout: top-middle
        title: Los Alamos National Laboratory
        link: https://www.lanl.gov/org/ddste/aldsc/theoretical/index.php
        link_text: Theoretical Division
        sub_title: Student Fellowship
        caption: June 2019 - August 2019
      - layout: top-middle
        title: Barcelona Supercomputing Center
        link: https://www.bsc.es/discover-bsc/organisation/scientific-structure/general-case
        link_text: CASE department
        sub_title: Research Engineer
        caption: September 2018 - September 2020

  - title: Publications and Preprints
    layout: text
    content: | # this will include new lines to allow paragraphs
      - <mark>Understanding quantum machine learning also requires rethinking generalization</mark>, Elies Gil-Fuster, Jens Eisert, and Carlos Bravo-Prieto, *in press Nature Communications* (2024). [[Preprint]](https://arxiv.org/abs/2306.13461)

      - <mark>Variational quantum linear solver</mark>, Carlos Bravo-Prieto, Ryan LaRose, Marco Cerezo, Yigit Subaşı, Lukasz Cincio, and Patrick J. Coles, *Quantum* **7**, 1188 (2023). [[Journal]](https://quantum-journal.org/papers/q-2023-11-22-1188/) [[Preprint]](https://arxiv.org/abs/1909.05820)
    
      - <mark>Style-based quantum generative adversarial networks for Monte Carlo events</mark>, Carlos Bravo-Prieto, Julien Baglio, Marco Cé, A. Francis, Dorota M. Grabowska, and Stefano Carrazza, *Quantum* **6**, 777 (2022). [[Journal]](https://quantum-journal.org/papers/q-2022-08-17-777/) [[Preprint]](https://arxiv.org/abs/2110.06933)
      
      - <mark>Variational quantum eigensolver for SU(N) fermions</mark>, Mirko Consiglio, Wayne J. Chetcuti, Carlos Bravo-Prieto, Sergi Ramos-Calderer, Anna Minguzzi, José I. Latorre, Luigi Amico, and Tony J. G. Apollaro, *Journal of Physics A: Mathematical and Theoretical* **55**, 265301 (2022). [[Journal]](https://iopscience.iop.org/article/10.1088/1751-8121/ac7016) [[Preprint]](https://arxiv.org/abs/2106.15552)
      
      - <mark>Solving systems of boolean multivariate equations with quantum annealing</mark>, Sergi Ramos-Calderer, Carlos Bravo-Prieto, Ruge Lin, Emanuele Bellini, Marc Manzano, Nawja Aaraj, and José I. Latorre, *Physical Review Research* **4**, 013096 (2022). [[Journal]](https://journals.aps.org/prresearch/abstract/10.1103/PhysRevResearch.4.013096) [[Preprint]](https://arxiv.org/abs/2111.13224)
      
      - <mark>Qibo: a framework for quantum simulation with hardware acceleration</mark>, Stavros Efthymiou, Sergi Ramos-Calderer, Carlos Bravo-Prieto, Adrián Pérez-Salinas, Diego García-Martín, Artur Garcia-Saez, José I. Latorre and Stefano Carrazza, *Quantum Science and Technology* **7**, 015018 (2021). [[Journal]](https://iopscience.iop.org/article/10.1088/2058-9565/ac39f5) [[Preprint]](https://arxiv.org/abs/2009.01845)
      
      - <mark>Quantum autoencoders with enhanced data encoding</mark>, Carlos Bravo-Prieto, *Machine Learning: Science and Technology* **2**, 035028 (2021). [[Journal]](https://iopscience.iop.org/article/10.1088/2632-2153/ac0616) [[Preprint]](https://arxiv.org/abs/2010.06599)
      
      - <mark>Quantum unary approach to option pricing</mark>, Sergi Ramos-Calderer, Adrián Pérez-Salinas, Diego García-Martín, Carlos Bravo-Prieto, Jorge Cortada, Jordi Planagumà, and José I. Latorre, *Physical Review A* **103**, 032414 (2020). [[Journal]](https://journals.aps.org/pra/abstract/10.1103/PhysRevA.103.032414) [[Preprint]](https://arxiv.org/abs/1912.01618)
      
      - <mark>Scaling of variational quantum circuit depth for condensed matter systems</mark>, Carlos Bravo-Prieto, Josep Lumbreras-Zarapico, Luca Tagliacozzo, and José I. Latorre, *Quantum* **4**, 272 (2020). [[Journal]](https://quantum-journal.org/papers/q-2020-05-28-272/) [[Preprint]](https://arxiv.org/abs/2002.06210)
      
      - <mark>Quantum singular value decomposer</mark>, Carlos Bravo-Prieto, Diego García-Martín, and José I. Latorre, *Physical Review A* **101**, 062310 (2020). [[Journal]](https://journals.aps.org/pra/abstract/10.1103/PhysRevA.101.062310) [[Preprint]](https://arxiv.org/abs/1905.01353)
      
      - <mark>Measuring the tangle of three-qubit states</mark>, Adrián Pérez-Salinas, Diego García-Martín, Carlos Bravo-Prieto, and José I. Latorre, *Entropy* **22**, 436 (2020). [[Journal]](https://www.mdpi.com/1099-4300/22/4/436) [[Preprint]](https://arxiv.org/abs/2003.06895)
      
# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

